---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - secrets.hazelart.fr
  resources:
  - secretgenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.hazelart.fr
  resources:
  - secretgenerators/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.hazelart.fr
  resources:
  - secretgenerators/status
  verbs:
  - get
  - patch
  - update
