# permissions for end users to view secretgenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretgenerator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-secrets-operator
    app.kubernetes.io/part-of: kubernetes-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretgenerator-viewer-role
rules:
- apiGroups:
  - secrets.hazelart.fr
  resources:
  - secretgenerators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.hazelart.fr
  resources:
  - secretgenerators/status
  verbs:
  - get
