apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kubernetes-secrets-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SecretGenerator is the Schema for the secretgenerators API
      displayName: Secret Generator
      kind: SecretGenerator
      name: secretgenerators.secrets.hazelart.fr
      version: v1alpha1
  description: Generate automatically your secrets.
  displayName: Kubernetes secrets operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - secrets
  - automation
  links:
  - name: Kubernetes Secrets Operator
    url: https://kubernetes-secrets-operator.domain
  maintainers:
  - email: thazelart@gmail.com
    name: thazelart
  maturity: alpha
  provider:
    name: thazelart.fr
    url: thazelart.github.io
  version: 0.0.0
